# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b49a2da23df8204bdb6dd11f87c5527f9601e37c49894f9ed438b4ed2c6bbf09e78b024ca3655a5bc2023409b382bbe2b9c29d055c83f5909116d95494c82eae

test:
  secret_key_base: 8b1d7b6d9ecc5da748de063197e9820a12839e1af88d58a1cb9945328a5f6744a33813e2ab5a4938c04c2d8345c5b59b65632ba4ea56ed1938f5e70c558ec2a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
